name: Build and Deploy OpenAPI v3.1 specification
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
# Have no job running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "./polyproto/package-lock.json"
      - name: Install TypeSpec and compile project
        run: |
          cd ./polyproto/
          npm install -g @typespec/compiler
          npm install
          tsp compile .
      - name: Commit OpenAPI specification to repository
        run: |
          tree -L 2
          mv -f ./polyproto/tsp-output/schema/3.0.0/* ./build/3.0.0/
          mv -f ./polyproto/tsp-output/schema/3.1.0/* ./build/3.1.0/
          git add ./build/*
          git commit -m "chore(bot): update openapi3 schema" || true
          git push || true
